export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE ='LOGOUT_USER_FAILURE'

export const GET_SINGLE_QUOTE_REQUEST = 'GET_SINGLE_QUOTE_REQUEST'
export const GET_SINGLE_QUOTE_SUCCESS = 'GET_SINGLE_QUOTE_SUCCESS'
export const GET_SINGLE_QUOTE_FAILURE = 'GET_SINGLE_QUOTE_FAILURE'